=== jdonref/jdonref/Dev/JPOIZONREFv3/web/META-INF/algosCP-Departements.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/algosCP-Departements.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE departements SYSTEM "algosCP-Departements.dtd">

    <departements>
    ...
    </departements>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT departements (codeDpt)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT codeDpt (algo)*>
<!ATTLIST codeDpt
    code CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT algo (param)*>
<!ATTLIST algo
    type CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT param (#PCDATA)>
<!ATTLIST param
    name CDATA #IMPLIED
  >

=== jdonref/jdonref/Dev/JDONREFv3v4/web/META-INF/algosCP-Departements.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : algosCP-Departements.xml
    Created on : 15 sept 2011
    Author     : waroche
    Description:
        Fichier des departements pour lesquels on ne peut determiner les prefixes de codes postaux 
		permetant d'identifier le departement d'appartenance.
		Pour chaque code departement concerne, on precise l'algorithme a utiliser et ses parametres.
-->
<!DOCTYPE Library  SYSTEM "./algosCP-Departements.dtd">
<departements>
    <codeDpt code="03">
		<algo type="fixed">
			<param name="prefix">03</param>
		</algo>
    </codeDpt>
    <codeDpt code="04">
		<algo type="fixed">
			<param name="prefix">04</param>
		</algo>
    </codeDpt>
    <codeDpt code="05">
		<algo type="fixed">
			<param name="prefix">05</param>
		</algo>
    </codeDpt>
    <codeDpt code="06">
		<algo type="fixed">
			<param name="prefix">06</param>
		</algo>
    </codeDpt>
    <codeDpt code="15">
		<algo type="fixed">
			<param name="prefix">15</param>
		</algo>
    </codeDpt>
    <codeDpt code="42">
		<algo type="fixed">
			<param name="prefix">42</param>
		</algo>
    </codeDpt>
    <codeDpt code="43">
		<algo type="fixed">
			<param name="prefix">43</param>
		</algo>
    </codeDpt>
    <codeDpt code="44">
		<algo type="fixed">
			<param name="prefix">44</param>
		</algo>
    </codeDpt>
    <codeDpt code="49">
		<algo type="fixed">
			<param name="prefix">49</param>
		</algo>
    </codeDpt>
    <codeDpt code="51">
		<algo type="fixed">
			<param name="prefix">51</param>
		</algo>
    </codeDpt>
    <codeDpt code="52">
		<algo type="fixed">
			<param name="prefix">52</param>
		</algo>
    </codeDpt>
    <codeDpt code="53">
		<algo type="fixed">
			<param name="prefix">53</param>
		</algo>
    </codeDpt>
    <codeDpt code="59">
		<algo type="fixed">
			<param name="prefix">59</param>
		</algo>
    </codeDpt>
    <codeDpt code="61">
		<algo type="fixed">
			<param name="prefix">61</param>
		</algo>
    </codeDpt>
    <codeDpt code="62">
		<algo type="fixed">
			<param name="prefix">62</param>
		</algo>
    </codeDpt>
    <codeDpt code="80">
		<algo type="fixed">
			<param name="prefix">80</param>
		</algo>
    </codeDpt>
</departements>
